---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - ns-vault-secrets-operator.yaml
  - ns-test-secrets.yaml
  - sub-vault-secrets-operator.yaml

  # Global Authentication
  - vaultauthglobal-default.yaml
  - vaultconnection-default.yaml
  - sa-static-auth.yaml

  # Per namespace auth config
  - vaultauth-vault-auth.yaml

  # Retrieve a Static Secret from Vault
  - vaultstaticsecret-vso-static.yaml

  # Retrieve a Certificate Signed by Vault
  - vaultpkisecret-vso-certificate.yaml
  - pod-vso-pki-cert-checker.yaml

  # Retrieve a generated Secret from Vault
  - vaultdynamicsecret-vso-dynamic.yaml

# helmCharts:
#   - name: mysql
#     repo: oci://registry-1.docker.io/bitnamicharts
#     version: 12.3.1
#     releaseName: mysql
#     namespace: test-secrets
#     valuesFile: mysql-values.yaml
