---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-secret
  namespace: test-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:

  # Matching the secret engine type
  type: kv-v2 

  # Mount path where the KV engine is enabled in Vault
  mount: secret

  # Path of the secret in Vault
  path: integration

  # Specify destination details for Kubernetes secret creation
  destination:
    name: vso-secret
    create: true

  # # Restart these pods when secrets rotated
  # hmacSecretData: true
  # rolloutRestartTargets:
  # - kind: Deployment
  #   name: vso-db-demo

  # Interval to refresh the static secret (ensure this matches operational requirements)
  refreshAfter: 30s

  # Name of the Vault authentication reference
  vaultAuthRef: vault-auth
