---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
  namespace: vault-secrets-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  address: https://hashicorp-vault-server-vault.apps.mgmt1.next.gmbros.local:8200

  # # optional configuration
  # # HTTP headers to be included in all Vault requests.
  # headers: []
  # # TLS server name to use as the SNI host for TLS connections.
  # tlsServerName: ""
  # # skip TLS verification for TLS connections to Vault.
  # skipTLSVerify: false
  # # the trusted PEM encoded CA certificate chain stored in a Kubernetes Secret
  # caCertSecretRef: ""