---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    openshift.io/cluster-monitoring: 'true'
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/warn: "privileged"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
