---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io.io/sync-option: ServerSideApply=true
spec:
  servingCerts:
    namedCertificates:
      - names:
        - "api.{{ .Values.clusterDomain }}"
        servingCertificate:
          name: api-certs
...
