---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # email: mail@example.com # Replace with your email
    skipTLSVerify: true
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - dns01:
        route53:
          accessKeyIDSecretRef:
            name: aws-creds
            key: aws_access_key_id
          region: eu-west-1
          secretAccessKeySecretRef:
            name: aws-creds
            key: aws_secret_access_key
